name: Aircall Image Resize CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AWS_REGION : "us-east-1"
  APPLICATION_NAME : "aircall-ecr-lambda"
permissions:
  id-token: write
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Build
      run: docker build . --file Dockerfile --tag latest
  
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Unit Tests
      shell: bash
      run: |
        echo "Product Development Unit Tests"
    - name: Integration Tests
      shell: bash
      run: |
        echo "Product Development Integration Tests"

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_GH_USER }}
        role-session-name: gh-env-deployment
        aws-region: ${{ env.AWS_REGION }}

    - name: Continuos Delivery
      shell: bash
      run: |
        echo "Deployment Stage"
        cd ..
        sh cicd/docker.sh ${{ secrets.AWS_ID }} ${AWS_REGION} ${env.APPLICATION_NAME}
      env:
          AWS_ID: ${{ secrets.AWS_ID }}
