name: AWS Cloud Deployment Framework

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AWS_REGION : "us-east-1"
  TF_WORK_DIR : "iac-framework/"
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    defaults:
      run:
        working-directory: ${{ env.TF_WORK_DIR }}
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_GH_USER }}
          role-session-name: gh-infrastructure
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

      - name: Cloud Formation Template File Bucket Update
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        shell: bash
        run: |
          echo "Copying cloud formation template file into s3 bucket"
          cd .. 
          cd iac-framework/cloudFormation/IAM-Role/
          aws s3 cp githubRole.yml s3://${{ secrets.S3_CLOUDFORMATION }}
      
      - name: Deploy to AWS CloudFormation
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        shell: bash
        run: |
          echo "Applying cloud formation"
          aws cloudformation deploy --template-file githubRole.yml --stack-name github-role-setup --capabilities CAPABILITY_IAM
