name: Aircall Image Resize CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Build
      run: docker build . --file Dockerfile --tag latest
  
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Unit Tests
      shell: bash
      run: |
        echo "Product Development Unit Tests"
    - name: Integration Tests
      shell: bash
      run: |
        echo "Product Development Integration Tests"

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.AWS_GH_USER }}

    - name: Continuos Delivery
      shell: bash
      run: |
        echo "Deployment Stage"
        cd ..
        sh cicd/docker.sh ${AWS_ID} ${REGION} ${APPLICATION_NAME}
      env:
          AWS_ID: ${{ secrets.AWS_ID }}
          REGION: us-east-1
          APPLICATION_NAME: aircall-ecr-lambda
